[log_files]
error_log = "src/logs/errors.log"
access_log = "src/logs/access.log"
events_limit = 128

[http]
access_log_format = "[{{time_local}}] - {{method}} {{status}} - {{bytes_sent}} kb - {{remote_user}} - {{remote_addr}}"
timeout = 1000                                                                                                      # milliseconds
size_limit = 10000                                                                                                   # kb

[http.servers]

[http.servers.server1]
ip_addr = "127.0.0.2"
hostname = "mylocalhost"
ports = [8082, 8083]
root_directory = "src/www"
error_path = "src/static_files/error.html"
default_file = "src/static_files/index.html"
cgi_file_format = ".py"
upload_limit = 5000
accepted_methods = ["GET"]
directory_listing = true
redirections = [
    { source = "/mouton", target = "/" },
    { source = "/chevre", target = "/" },
]
exclusion = [""]

[http.servers.server2]
ip_addr = "127.0.0.10"
hostname = "fifanela"
ports = [8080, 8081]
root_directory = "src/www/fifanela"
error_path = "src/static_files/error.html"
default_file = "src/static_files/index.html"
cgi_file_format = ".py"
upload_limit = 5000
accepted_methods = ["GET", "POST","PUT"]
directory_listing = true
redirections = [
    { source = "/mouton", target = "/" },
    { source = "/chevre", target = "/" },
    { source = "/a", target = "/b" },
    { source = "/b", target = "/a" },
]
exclusion = []
